/*
 * GpsSplitterFrame.java
 *
 * Created on 18-Jan-2011, 09:26:42
 */
package gpxsplitter;

import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author anc6
 */
public class UI extends javax.swing.JFrame
{

    Controller controller;

    /** Creates new form GpsSplitterFrame */
    public UI()
    {
        initComponents();
        populateOutputGpxFormats();
    }

    UI(Controller controller)
    {
        this();
        this.controller = controller;
    }

    /** This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel topPanel = new javax.swing.JPanel();
        openFileField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        javax.swing.JLabel fileTypeLabel = new javax.swing.JLabel();
        fileTypeValue = new javax.swing.JLabel();
        javax.swing.JPanel middlePanel = new javax.swing.JPanel();
        javax.swing.JLabel instrNumLabel = new javax.swing.JLabel();
        instrNumField = new javax.swing.JTextField();
        javax.swing.JLabel gpxTypeLabel = new javax.swing.JLabel();
        gpxTypeComboBox = new javax.swing.JComboBox();
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        javax.swing.JLabel fileNameLabel = new javax.swing.JLabel();
        fileNameField = new javax.swing.JTextField();
        javax.swing.JLabel emptyLabel = new javax.swing.JLabel();
        saveFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        topPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Open Gpx file"));
        topPanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        openFileField.setEnabled(false);
        topPanel.add(openFileField);

        browseButton.setText("Browse...");
        topPanel.add(browseButton);

        fileTypeLabel.setText("Loaded gpx:");
        topPanel.add(fileTypeLabel);

        fileTypeValue.setText("N/A");
        topPanel.add(fileTypeValue);

        getContentPane().add(topPanel);

        middlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Gpx"));
        middlePanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        instrNumLabel.setText("Instructions / file:");
        middlePanel.add(instrNumLabel);

        instrNumField.setText("125");
        middlePanel.add(instrNumField);

        gpxTypeLabel.setText("Gpx type:");
        middlePanel.add(gpxTypeLabel);

        gpxTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Track", "Route" }));
        middlePanel.add(gpxTypeComboBox);

        getContentPane().add(middlePanel);

        bottomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New gpx name"));
        bottomPanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        fileNameLabel.setText("File name:");
        bottomPanel.add(fileNameLabel);
        bottomPanel.add(fileNameField);
        bottomPanel.add(emptyLabel);

        saveFileButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        saveFileButton.setText("Split");
        bottomPanel.add(saveFileButton);

        getContentPane().add(bottomPanel);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-323)/2, 416, 323);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JLabel fileTypeValue;
    private javax.swing.JComboBox gpxTypeComboBox;
    private javax.swing.JTextField instrNumField;
    private javax.swing.JTextField openFileField;
    private javax.swing.JButton saveFileButton;
    // End of variables declaration//GEN-END:variables

    void setController(Controller controller)
    {
        this.controller = controller;
    }

    /***
     * Miniature observer/Observable pattern
     * @param gpx Used to populate the UI
     */
    public void update(Gpx gpx)
    {
        fileTypeValue.setText("Gpx " + gpx.getType() + " " + gpx.getVersion() + " (" + gpx.getNumOfInstructions() + " instructions)");
        openFileField.setText(gpx.getFilePath());
    }

    GpxFormat getSelectedGpxType()
    {
        return (GpxFormat) gpxTypeComboBox.getSelectedItem();
    }

    private void populateOutputGpxFormats()
    {
        gpxTypeComboBox.removeAllItems(); // Clear and repopulate from the enum
        for (GpxFormat format : GpxFormat.values())
        {
            gpxTypeComboBox.addItem(format);
        }
    }

    void gpxSavedSuccessfully()
    {
        JOptionPane.showMessageDialog(this, "Split GPX successfully saved.",
                "Information", JOptionPane.INFORMATION_MESSAGE);
    }

    JButton getBrowseButton()
    {
        return browseButton;
    }

    JButton getSaveFileButton()
    {
        return saveFileButton;
    }

    String getInstructionsNumber()
    {
        return instrNumField.getText();
    }

    String getHighlightedGpxType()
    {
        return gpxTypeComboBox.getSelectedItem().toString();
    }

    String getNewGpxFileName()
    {
        return fileNameField.getText();
    }
}
